### ISSUE TITLE
Last day excluded from monthly leaderboard

### ISSUE THREAD

**Issue by Meziu** [JJK96/srb2_highscores#51]
https://github.com/JJK96/srb2_highscores/blob/acc3ea6a2f2c32ab213ce58dafcd55625bb8ce4c/client/src/routes/Leaderboard.svelte#L22

SQL filters from the “morning”’s midnight of the selected day, which means that the last day of the selected time period gets cut from the filtering. 

The line mentioned should be this instead:
```javascript
var last_day  = new Date(year, month+1, 1)
```

A similar fix should be made for my Discord bot.

**Comment by JJK96** [comment]
Can you make a PR for this?

**Comment by Meziu** [comment]
> Can you make a PR for this?

Yeah I will once I get time, I made this issue just as a reminder. 😅

**Comment by Meziu** [comment]
I fixed the discord bot as well.

**Comment by JJK96** [comment]
Thank you!
